// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeMessage() string {
	foo := provideFoo()
	string2 := foo.S
	return string2
}
