// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeBar() Bar {
	myFooer := provideMyFooer()
	bar := provideBar(myFooer)
	return bar
}
