// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"os"
)

// Injectors from wire.go:

func InitializeFile(path Path) (*os.File, func(), error) {
	logger := provideLogger()
	file, cleanup, err := provideFile(logger, path)
	if err != nil {
		return nil, nil, err
	}
	return file, func() {
		cleanup()
	}, nil
}
